### ISSUE TITLE
稀疏化训练几个数据后,准确率1,loss nan

### ISSUE THREAD

**Issue by QW-Is-Here** [talebolano/yolov3-network-slimming#23]
有遇到过这个问题的吗？我在 `coco` 和 `oxfordhand` data上面都是这样
![image](https://user-images.githubusercontent.com/31319863/61096781-c27a0580-a426-11e9-90ee-dbc9e36b1a45.png)
![image](https://user-images.githubusercontent.com/31319863/61096816-d160b800-a426-11e9-893c-893a76c02a4e.png)

**Comment by lizhaokun** [comment]
你看看你的cfg配置文件选的是test还是train，batch和subdivisions等于1的时候是没有效果的
